### PR TITLE
Update readme to start notebook with allow_origin

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by blink1073** [comment]
The demo runner is already doing this: https://github.com/blink1073/jupyter_demo/blob/master/main.py#L31.

**Comment by Carreau** [comment]
Hum, I missed that and it was not working for me... let me try to figure out why..

**Comment by blink1073** [comment]
It implicitly relies on being there being no other notebook servers running (because we hard-code 8888 in the demo).

**Comment by blink1073** [comment]
(Which should be made explicit, I just forgot).

**Comment by Carreau** [comment]
> It implicitly relies on being there being no other notebook servers running (because we hard-code 8888 in the demo).

I did not have any there notebook running, but I might had some specific config/password that where preventing connection.

**Pull request closed without merging**
